pinaxcon/registrasion/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    "pinaxcon.registrasion.views",
    url(r"^demopay/([0-9]+)/([A-Z0-9]+)$", views.demopay, name="demopay"),
)

pinaxcon/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.contrib.flatpages.views import flatpage

from django.contrib import admin

import symposion.views


urlpatterns = [
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^conference/", include("symposion.conference.urls")),

    url(r"^teams/", include("symposion.teams.urls")),

    # Required by registrasion
    url(r'^tickets/payments/', include('registripe.urls')),
    url(r'^tickets/', include('registrasion.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^checkin/', include('regidesk.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    url(r'^dashboard/', symposion.views.dashboard, name="dashboard"),
    url(r'^boardingpass', RedirectView.as_view(pattern_name="regidesk:boardingpass")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/proposals/models.py
from django.db import models

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    TARGET_USER = 1
    TARGET_BUSINESS = 2
    TARGET_COMMUNITY = 3
    TARGET_DEVELOPER = 4

    TARGET_AUIDENCES = [
        (TARGET_USER, "User"),
        (TARGET_BUSINESS, "Business"),
        (TARGET_COMMUNITY, "Community"),
        (TARGET_DEVELOPER, "Developer"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUIDENCES)

    recording_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any recordings of "
        "presentations covered by this proposal, under the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    materials_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any other material "
        "(such as slides) from presentations covered by this proposal, under "
        "the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    class Meta:
        abstract = True


class TalkProposal(Proposal):

    class Meta:
        verbose_name = "talk proposal"


class TutorialProposal(Proposal):

    class Meta:
        verbose_name = "tutorial proposal"


class MiniconfProposal(Proposal):

    target_audience = models.IntegerField(choices=Proposal.TARGET_AUIDENCES,
                                          default=Proposal.TARGET_DEVELOPER)

    class Meta:
        verbose_name = "miniconf proposal"


class SysAdminProposal(Proposal):

    TYPE_SHORT_PRESENTATION = 1
    TYPE_LIGHTNING_TALK = 2

    TALK_FORMATS = [
        (TYPE_SHORT_PRESENTATION, "Short Presentation (15-25 min)"),
        (TYPE_LIGHTNING_TALK, "Lightning Talk (5-10 min)"),
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        help_text="Please indicate your preferred talk length in the private abstract field below.")

    class Meta:
        verbose_name = "System Administration Miniconf Proposal"


class KernelProposal(Proposal):

    class Meta:
        verbose_name = "Kernel Miniconf Proposal"


class GamesProposal(Proposal):

    TYPE_PRESENTATION = 1
    TYPE_DEMONSTRATION = 2
    TYPE_OTHER = 3

    TALK_FORMATS = [
        (TYPE_PRESENTATION, "Presentation"),
        (TYPE_DEMONSTRATION, "Demonstration"),
        (TYPE_OTHER, "Other"),
    ]

    talk_format = models.IntegerField(choices=TALK_FORMATS)

    class Meta:
        verbose_name = "Games and FOSS Miniconf Proposal"


class OpenHardwareProposal(Proposal):

    TYPE_NORMAL_PRESENTATION = 1
    TYPE_LIGHTNING_TALK = 2

    TALK_FORMATS = [
        (TYPE_NORMAL_PRESENTATION, "Presentation (20 min)"),
        (TYPE_LIGHTNING_TALK, "Lightning Talk (5 min)"),
    ]

    talk_format = models.IntegerField(choices=TALK_FORMATS)

    class Meta:
        verbose_name = "Open Hardware Miniconf Proposal"


class ClsXLCAProposal(Proposal):

    class Meta:
        verbose_name = "CLSxLCA Miniconf Proposal"


class FuncProgProposal(Proposal):

    class Meta:
        verbose_name = "Real World Functional Programming Miniconf Proposal"


class OpenEdProposal(Proposal):

    class Meta:
        verbose_name = "Open Education Miniconf Proposal"


class OpenGLAMProposal(Proposal):

    class Meta:
        verbose_name = "OpenGLAM Miniconf Proposal"


class FPGAProposal(Proposal):

    class Meta:
        verbose_name = "FPGA Miniconf Proposal"


class DevDevProposal(Proposal):

    class Meta:
        verbose_name = "Developers Developers Miniconf Proposal"


class ArtTechProposal(Proposal):

    TYPE_TECH = 1
    TYPE_DEMO = 2
    TYPE_LIGHTNING = 3

    TALK_FORMATS = [
        (TYPE_TECH, "Tech talk (45 min)"),
        (TYPE_DEMO, "Demonstration (20min)"),
        (TYPE_LIGHTNING, "Lightning Talk (10min)"),
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        default=TYPE_TECH,
    )

    EXHIBIT_YES = 1
    EXHIBIT_NO = 2

    EXHIBIT_STATUS = [
        (EXHIBIT_YES, "I am willing and able to exhibit my project on Monday, January 22nd"),
        (EXHIBIT_NO, "I'm unable to exhibit my project")
    ]

    can_exhibit = models.IntegerField(
        choices=EXHIBIT_STATUS,
        default=EXHIBIT_YES,
    )

    exhibition_requirements = models.TextField(
        blank=True,
        default="",
    )

    TARGET_NA = 1

    TARGET_AUDIENCES = [
        (TARGET_NA, "N/A"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUDIENCES, default=TARGET_NA)

    # def __init__(self, *args, **kwargs):
    #     super(ArtTechProposal, self).__init__(*args, **kwargs)
    #     self.target_audience = 3

    class Meta:
        verbose_name = "Art+Tech Miniconf Proposal"


class BioInformaticsProposal(Proposal):

    class Meta:
        verbose_name = "Open Source and BioInformatics Miniconf"

pinaxcon/proposals/forms.py
import copy

from django import forms

from pinaxcon.proposals.models import TalkProposal, TutorialProposal, MiniconfProposal
from pinaxcon.proposals.models import SysAdminProposal, KernelProposal, OpenHardwareProposal
from pinaxcon.proposals.models import GamesProposal, ClsXLCAProposal, FuncProgProposal
from pinaxcon.proposals.models import OpenEdProposal, OpenGLAMProposal, FPGAProposal, DevDevProposal
from pinaxcon.proposals.models import ArtTechProposal, BioInformaticsProposal

DEFAULT_FIELDS =  [
    "title",
    "target_audience",
    "abstract",
    "private_abstract",
    "technical_requirements",
    "project",
    "project_url",
    "recording_release",
    "materials_release",
]

TALK_FORMAT_FIELDS = copy.copy(DEFAULT_FIELDS)
TALK_FORMAT_FIELDS.append("talk_format")

class ProposalForm(forms.ModelForm):

    required_css_class = 'label-required'

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class MiniconfProposalForm(ProposalForm):

    class Meta:
        model = MiniconfProposal
        fields = [
            "title",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "recording_release",
            "materials_release",
        ]

class SysadminProposalForm(ProposalForm):

    class Meta:
        model = SysAdminProposal
        fields = TALK_FORMAT_FIELDS

class KernelProposalForm(ProposalForm):

    class Meta:
        model = KernelProposal
        fields = DEFAULT_FIELDS

class GamesProposalForm(ProposalForm):

    class Meta:
        model = GamesProposal
        fields = TALK_FORMAT_FIELDS

class OpenHardwareProposalForm(ProposalForm):

    class Meta:
        model = OpenHardwareProposal
        fields = TALK_FORMAT_FIELDS

class ClsXLCAProposalForm(ProposalForm):

    class Meta:
        model = ClsXLCAProposal
        fields = DEFAULT_FIELDS

class FuncProgProposalForm(ProposalForm):

    class Meta:
        model = FuncProgProposal
        fields = DEFAULT_FIELDS

class OpenEdProposalForm(ProposalForm):

    class Meta:
        model = OpenEdProposal 
        fields = DEFAULT_FIELDS

class OpenGLAMProposalForm(ProposalForm):

    class Meta:
        model = OpenGLAMProposal
        fields = DEFAULT_FIELDS

class FPGAProposalForm(ProposalForm):

    class Meta:
        model = FPGAProposal
        fields = DEFAULT_FIELDS

class DevDevProposalForm(ProposalForm):

    class Meta:
        model = DevDevProposal
        fields = DEFAULT_FIELDS

class ArtTechProposalForm(ProposalForm):

    class Meta:
        ARTTECH_FIELDS = copy.copy(DEFAULT_FIELDS)
        ARTTECH_FIELDS.remove("target_audience")
        ARTTECH_FIELDS.append("talk_format")
        ARTTECH_FIELDS.append("can_exhibit")
        ARTTECH_FIELDS.append("exhibition_requirements")

        model = ArtTechProposal
        fields = ARTTECH_FIELDS

class BioInformaticsProposalForm(ProposalForm):

    class Meta:
        model = BioInformaticsProposal
        fields = DEFAULT_FIELDS

pinaxcon/registrasion/forms.py
from pinaxcon.registrasion import models

from django import forms


class YesNoField(forms.TypedChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs['required'] = True
        super(YesNoField, self).__init__(
            *args,
            coerce=lambda x: x in ['True', 'Yes', True],
            choices=((None, '--------'), (False, 'No'), (True, 'Yes')),
            **kwargs
        )


class ProfileForm(forms.ModelForm):
    ''' A form for requesting badge and profile information. '''

    required_css_class = 'label-required'

    class Meta:
        model = models.AttendeeProfile
        exclude = ['attendee']
        widgets = {
            'past_lca': forms.widgets.CheckboxSelectMultiple
        }
        field_classes = {
            "of_legal_age": YesNoField,
        }

pinaxcon/registrasion/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from registrasion import models as rego
from registrasion.controllers.invoice import InvoiceController

from pinaxcon.registrasion import models


def demopay(request, invoice_id, access_code):
    ''' Marks the invoice with the given invoice id as paid.
    '''
    invoice_id = int(invoice_id)
    inv = get_object_or_404(rego.Invoice.objects, pk=invoice_id)

    invoice = InvoiceController(inv)

    if not invoice.can_view(user=request.user, access_code=access_code):
        raise Http404()

    to_invoice = redirect("invoice", invoice.invoice.id, access_code)

    try:
        invoice.validate_allowed_to_pay()  # Verify that we're allowed to do this.
    except ValidationError as ve:
        messages.error(request, ve.message)
        return to_invoice

    # Create the payment object
    models.DemoPayment.objects.create(
        invoice=invoice.invoice,
        reference="Demo payment by user: " + request.user.username,
        amount=invoice.invoice.value,
    )

    invoice.update_status()

    messages.success(request, "This invoice was successfully paid.")

    return to_invoice

pinaxcon/views.py
from django.shortcuts import render, redirect

from account.decorators import login_required
from symposion.proposals.models import ProposalSection


@login_required
def dashboard(request):
    """
    Copy of symposion.views.dashboard modified to inject available proposal
    kinds into the request context.
    """

    if request.session.get("pending-token"):
        return redirect("speaker_create_token", request.session["pending-token"])


    sections = ProposalSection.available().prefetch_related('section__proposal_kinds')
    kinds = [k for kind in section for k in section.proposal_kinds]
    return render(request, "dashboard.html", {'kinds': kinds})

pinaxcon/templates/symposion/reviews/_result_notification_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} proposal.title {% templatetag closevariable %}</code> e.g. {{ proposals.0.title }}
    <li><code>{% templatetag openvariable %} proposal.kind {% templatetag closevariable %}</code> e.g. {{ proposals.0.kind }}
    <li><code>{% templatetag openvariable %} proposal.main_speaker {% templatetag closevariable %}</code> e.g. {{ proposals.0.speaker }}
    <li><code>{% templatetag openvariable %} proposal.speakers {% templatetag closevariable %}</code> e.g. {{ proposals.0.speakers|join:", " }}
    <li><code>{% templatetag openvariable %} proposal.additional_speakers {% templatetag closevariable %}</code> e.g. {{ proposals.0.additional_speakers }}
</ul>

pinaxcon/templates/symposion/reviews/_review_table.html
{% load i18n %}

<table class="table table-striped table-reviews">
    <thead>
        <th>#</th>
        <th>{% trans "Speaker / Title" %}</th>
        <th class="toggle">Audience</th>
        <th class="toggle">Format</th>
        <th>{% trans "Votes" %}</th>
        <th class="toggle">{% trans "Score" %}</th>
        <th class="votes">{% trans "+2" %}</th>
        <th class="votes">{% trans "+1" %}</th>
        <th class="votes">{% trans "-1" %}</th>
        <th class="votes">{% trans "-2" %}</th>
        <th><a href="#" class="tip" title="{% trans "Your Rating" %}"><i class="fa fa-user"></i></a></th>
    </thead>

    <tbody>
        {% for proposal in proposals %}
            <tr class="{{ proposal.user_vote_css }}">
                <td>{{ proposal.number }}</td>
                <td>
                    <a href="{% url "review_detail" proposal.pk %}">
                        <small><strong>{{ proposal.speaker }}</strong></small>
                        <br />
                        {{ proposal.title }}
                    </a>
                </td>
                <td>{{ proposal.get_target_audience_display }}</td>
                <td>{{ proposal.get_talk_format_display }}</td>
                <td>{{ proposal.total_votes }}</td>
                <td>{{ proposal.score }}</td>
                <td>{{ proposal.plus_two }}</td>
                <td>{{ proposal.plus_one }}</td>
                <td>{{ proposal.minus_one }}</td>
                <td>{{ proposal.minus_two }}</td>
                <td>{{ proposal.user_vote|default:"" }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

pinaxcon/templates/symposion/reviews/access_not_permitted.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Access Not Permitted</h1>

    <p>
        Sorry, you do not have permission to access this page. If you
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

pinaxcon/templates/symposion/reviews/base.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% load i18n %}

{% block body_class %}reviews{% endblock %}

{% block body_outer %}
<div class="row text-primary">
    <div class="col-md-4">
        {% block sidebar %}
        {% for section in review_sections %}
        <div class="card card-default mb-4">
            <div class="card-header">
                <h3 class="card-title">{{ section }}</h3>
            </div>
            <div class="list-group">
                <a class="list-group-item review-list" href="{% url "review_section" section.section.slug %}">
                    {% trans "All Reviews" %}
                </a>
                {% comment %}
                <li>
                    <a href="{% url "review_section_assignments" section.section.slug %}">
                        {% trans "Your Assignments" %}
                    </a>
                </li>
                {% endcomment %}
                <a class="list-group-item user-reviewed" href="{% url "user_reviewed" section.section.slug %}">
                    {% trans "Reviewed by you" %}
                </a>
                <a class="list-group-item user-not-reviewed" href="{% url "user_not_reviewed" section.section.slug %}">
                    {% trans "Unreviewed by you" %}
                </a>
                <a class="list-group-item user-random" href="{% url "user_random" section.section.slug %}">
                    {% trans "Random unreviewed proposal" %}
                </a>
                <a class="list-group-item voting-status" href="{% url "review_status" section.section.slug %}">
                    {% trans "Voting Status" %}
                </a>
                {% if request.user.is_staff %}
                <a class="list-group-item review-results" href="{% url "result_notification" section.section.slug 'accepted' %}">Result Notification</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% endblock %}
    </div>
    
    
    <div class="col-md-8">
        {% block body %}
        {% endblock %}
    </div>
</div>

{% endblock %}
{% block extra_script %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $("table.table-reviews").dataTable({
        "stateSave": true,
        "lengthMenu": [[10, 50, 100, -1], [10, 50, 100, "All"]],
        "pageLength": 100,
        "colReorder": true,
        "buttons": [{
            extend: 'collection',
            text: 'Export',
            buttons: ["copy", "csv", "print"]
        },
        { extend: 'collection',
        text: 'Columns',
        buttons: [
        { extend: 'columnsToggle',
        columns: '.toggle' },
        { extend: 'columnToggle',
        text: 'Vote details',
        columns: '.votes'
    }
    ]
}]});
</script>
{% endblock %}

pinaxcon/templates/symposion/reviews/result_notification.html
{% extends "symposion/reviews/base.html" %}

{% load i18n %}


{% block body_class %}{{ block.super }} review-results{% endblock %}

{% block extra_style %}
{{ block.super }}
    <style type="text/css">
        .table-striped tbody tr.selected td {
            background-color: #F7F4E6;
        }
    </style>
{% endblock %}

{% block body %}

    <ul class="nav nav-pills">
        <li{% if status == 'accepted' %} class="active"{% endif %}><a href="{% url "result_notification" section_slug 'accepted' %}">accepted</a>
        <li{% if status == 'rejected' %} class="active"{% endif %}><a href="{% url "result_notification" section_slug 'rejected' %}">rejected</a>
        <li{% if status == 'standby' %} class="active"{% endif %}><a href="{% url "result_notification" section_slug 'standby' %}">standby</a>
    </ul>

    <h1>Result Notification</h1>

    <form class="form-horizontal" method="post" action="{% url "result_notification_prepare" section_slug status %}">

        {% csrf_token %}

        <p>
            Select one or more proposals (<span class="action-counter">0</span> currently selected)
            <br/>
            then pick an email template
            <select name="notification_template">
                <option value="">[blank]</option>
                {% for template in notification_templates %}
                    <option value="{{ template.pk }}">{{ template.label }}</option>
                {% endfor %}
            </select>
            <br/>
            <button id="next-button" type="submit" class="btn btn-primary" disabled>Next <i class="fa fa-chevron-right"></i></button>
        </p>

        <table class="table table-striped table-bordered table-reviews">
            <thead>
                <th><input type="checkbox" id="action-toggle"></th>
                <th>#</th>
                <th>{% trans "Speaker / Title" %}</th>
                <th>{% trans "Category" %}</th>
                <th>{% trans "Status" %}</th>
                <th>{% trans "Notified?" %}</th>
            </thead>

            <tbody>
                {% for proposal in proposals %}
                    <tr>
                        <td><input class="action-select" type="checkbox" name="_selected_action" value="{{ proposal.pk }}"></td>
                        <td>{{ proposal.number }}</td>
                        <td>
                            <a href="{% url "review_detail" proposal.pk %}">
                                <small><strong>{{ proposal.speaker }}</strong></small>
                                <br />
                                {{ proposal.title }}
                            </a>
                        </td>
                        <td>{{ proposal.track }}</td>
                        <td>
                            {% with proposal.result.status as status %}
                                <div class="{{ status }}">
                                    {% if status != "undecided" %}
                                        <span>{{ status }}</span>
                                    {% endif %}
                                </div>
                            {% endwith %}
                        </td>
                        <td>
                            {% if proposal.notifications.exists %}yes{% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

{% block extra_script %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-flash-1.4.2/b-html5-1.4.2/b-print-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/r-2.2.0/rg-1.0.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-html5-1.4.2/b-print-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/r-2.2.0/rg-1.0.2/datatables.min.js"></script>
    <script type="text/javascript">
        (function($) {
            $.fn.actions = function(opts) {
                var options = $.extend({}, $.fn.actions.defaults, opts);
                var actionCheckboxes = $(this);
                checker = function(checked) {
                    $(actionCheckboxes).prop("checked", checked)
                        .parent().parent().toggleClass(options.selectedClass, checked);
                }
                updateCounter = function() {
                    var sel = $(actionCheckboxes).filter(":checked").length;
                    $(options.counterContainer).html(sel);
                    $(options.allToggle).prop("checked", function() {
                        if (sel == actionCheckboxes.length) {
                            value = true;
                        } else {
                            value = false;
                        }
                        return value;
                    });
                    if (sel == 0) {
                        $("#next-button").prop("disabled", true);
                    } else {
                        $("#next-button").prop("disabled", false);
                    }
                }
                // Check state of checkboxes and reinit state if needed
                $(this).filter(":checked").each(function(i) {
                    $(this).parent().parent().toggleClass(options.selectedClass);
                    updateCounter();
                });
                $(options.allToggle).click(function() {
                    checker($(this).prop("checked"));
                    updateCounter();
                });
                lastChecked = null;
                $(actionCheckboxes).click(function(event) {
                    if (!event) { var event = window.event; }
                    var target = event.target ? event.target : event.srcElement;
                    if (lastChecked && $.data(lastChecked) != $.data(target) && event.shiftKey == true) {
                        var inrange = false;
                        $(lastChecked).prop("checked", target.checked)
                            .parent().parent().toggleClass(options.selectedClass, target.checked);
                        $(actionCheckboxes).each(function() {
                            if ($.data(this) == $.data(lastChecked) || $.data(this) == $.data(target)) {
                                inrange = (inrange) ? false : true;
                            }
                            if (inrange) {
                                $(this).prop("checked", target.checked)
                                    .parent().parent().toggleClass(options.selectedClass, target.checked);
                            }
                        });
                    }
                    $(target).parent().parent().toggleClass(options.selectedClass, target.checked);
                    lastChecked = target;
                    updateCounter();
                });
            }
            /* Setup plugin defaults */
            $.fn.actions.defaults = {
                counterContainer: "span.action-counter",
                allToggle: "#action-toggle",
                selectedClass: "selected"
            }
        })($);
        $(function() {
            $("tr input.action-select").actions();
        });
        $('.dataTable').dataTable({
            "dom": "<'row'<'col-md-3'l><'col-md-3'B><'col-md-4'f>r>t<'row'<'col-md-3'i><'col-md-5'p>>",
            "stateSave": true,
            "lengthMenu": [[10, 50, 100, -1], [10, 50, 100, "All"]],
            "drawCallback": function( settings ) {
                $("tr input.action-select").actions();
            },
            "pageLength": 100,
            "colReorder": true,
            "buttons": [ {
              extend: 'collection',
              text: 'Export',
              buttons: ["copy", "csv", "print"]
            },
            { extend: 'collection',
              text: 'Columns',
              buttons: [
                { extend: 'columnsToggle',
                  columns: '.toggle' },
                { extend: 'columnToggle',
                  text: 'Vote details',
                  columns: '.votes'
                }
            ]
        }]});
    </script>
{% endblock %}

pinaxcon/templates/symposion/reviews/review_admin.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Reviewers – {{ section_slug }}</h1>

    <table class="table table-striped">
        <tr>
            <th>
                Reviewer
            </th>
            <th>
                Proposals<br/>Reviewed
            </td>
            <th>
                Comments
            </th>
            <th>
                Avg
            </th>
            <th>
                +2
            </th>
            <th>
                +1
            </th>
            <th>
                &minus;1
            </th>
            <th>
                &minus;2
            </th>
            <th>
                Abstain
            </th>
        </tr>
        {% for reviewer in reviewers %}
        <tr>
            <td>
                <a href="{% url "review_list_user" section_slug reviewer.pk %}">
                    {{ reviewer.get_full_name }} &lt;{{ reviewer.email }}&gt;
                </a>
            </td>
            <td>
                {{ reviewer.total_votes }}
            </td>
            <td>
                {{ reviewer.comment_count }}
            </td>
            <td>
                {{ reviewer.average|floatformat:2 }}
            </td>
            <td>
                {{ reviewer.plus_two }}
            </td>
            <td>
                {{ reviewer.plus_one }}
            </td>
            <td>
                {{ reviewer.minus_one }}
            </td>
            <td>
                {{ reviewer.minus_two }}
            </td>
            <td>
                {{ reviewer.abstain }}
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}